/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package materias;

import java.awt.Image;
import javax.swing.ImageIcon;
import jroundborder.JLabelRound;

/**
 *
 * @author aniel
 */
public class Cargando extends javax.swing.JFrame {

    /**
     * Creates new form Cargando
     */
    JLabelRound labelCircular = new JLabelRound();
    int size = 135;
    ImageIcon icon;
    Image image;

    public Cargando() {
        initComponents();

        try {
            this.setLocationRelativeTo(null);
            labelCircular.setBounds(23, 23, size, size);
//            labelCircular.setSize(200, 200);
            icon = new ImageIcon(getClass().getResource("/Imagenes/ITL.png"));
            image = Imagenes.getScaledImage(icon.getImage(), this.labelCircular.getWidth(), this.labelCircular.getHeight());
            this.labelCircular.setIcon(new ImageIcon(image));
            jPanel1.add(labelCircular);
//            icon = new ImageIcon(getClass().getResource("/Imagenes/loading.gif"));
//            image = Imagenes.getScaledImage(icon.getImage(), jLabLoad.getWidth(), jLabLoad.getHeight());
//            this.jLabLoad.setIcon(new ImageIcon(image));
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabLoad = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabEspere = new javax.swing.JLabel();
        jLabFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loading.gif"))); // NOI18N
        getContentPane().add(jLabLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, 180));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 180));

        jLabEspere.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabEspere.setText("CARGANDO, ESPERE UN MOMENTO...");
        getContentPane().add(jLabEspere, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabFondo.setBackground(new java.awt.Color(255, 255, 255));
        jLabFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabFondo.setOpaque(true);
        getContentPane().add(jLabFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cargando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cargando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cargando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cargando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cargando().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabEspere;
    private javax.swing.JLabel jLabFondo;
    private javax.swing.JLabel jLabLoad;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
